stages:
  - test
  - build
  - integrate

.rules: &rules
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success

build binary:
  stage: build
  needs: []
  dependencies: []
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/go-ubuntu:1.20-rolling
  variables:
    GOFLAGS: "-buildvcs=false"
  script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ci -a -installsuffix cgo -ldflags '-extldflags "-static"' main.go
  artifacts:
    paths:
      - ci
  <<: *rules

integrate ko:
  stage: integrate
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/go-ubuntu:1.20-rolling
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/go
    BUILD_IMAGE_PARENT: harbor.dcas.dev/gcr.io/distroless/static-debian11:nonroot
  cache:
    paths:
      - .cache
    key: ko
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
  script:
    - |
      mkdir -p bin/
      mv ci bin/
      export PATH="$PATH:$CI_PROJECT_DIR/bin"
      
      wget -qO- "https://github.com/ko-build/ko/releases/download/v0.12.0/ko_0.12.0_Linux_x86_64.tar.gz" | tar -xvz ko
      install ./ko "$CI_PROJECT_DIR/bin/ko"
    - ci build --recipe com.github.google.ko
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

integrate jib:
  stage: integrate
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/maven:19
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/java-maven
    AUTO_DEVOPS_MAVEN_SETTINGS_ARGS: "-mirror=prism=Prism=https://prism.v2.dcas.dev/api/v1/maven/-/=central"
    BUILD_IMAGE_PARENT: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/tomcat-native:19
  cache:
    paths:
      - .cache
    key: mvn
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
  script:
    - |
      mkdir -p ~/.m2
      /opt/mvn-settings-gen ${AUTO_DEVOPS_MAVEN_SETTINGS_ARGS} > ~/.m2/settings.xml
    - ./ci build --recipe com.google.cloud.tools.jib-maven-plugin
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

integrate buildkit:
  stage: integrate
  image: harbor.dcas.dev/docker.io/moby/buildkit:v0.11.3-rootless
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/python
    KUBERNETES_POD_ANNOTATIONS_1: "container.apparmor.security.beta.kubernetes.io/build=unconfined"
    KUBERNETES_POD_ANNOTATIONS_2: "container.seccomp.security.alpha.kubernetes.io/build=unconfined"
  cache:
    paths:
      - .cache
    key: buildkit
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
  script:
    - ./ci build --recipe com.github.moby.buildkit
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules
