stages:
  - test
  - verify
  - build
  - integrate

.rules: &rules
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success

build binary:
  stage: build
  needs: []
  dependencies: []
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/go-ubuntu:1.20-rolling
  variables:
    GOFLAGS: "-buildvcs=false"
    GOPATH: $CI_PROJECT_DIR/.go
  script:
    - mkdir -p .go
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ci -a -installsuffix cgo -ldflags '-extldflags "-static"' main.go
  cache:
    key: golang
    paths:
      - .go/pkg/mod
  artifacts:
    paths:
      - ci
  <<: *rules

integrate ko:
  stage: integrate
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/go-ubuntu:1.20-rolling
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/go
    BUILD_IMAGE_PARENT: harbor.dcas.dev/gcr.io/distroless/static-debian11:nonroot
  cache:
    paths:
      - .cache
    key: ko
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
      - build.txt
  script:
    - |
      mkdir -p bin/
      mv ci bin/
      export PATH="$PATH:$CI_PROJECT_DIR/bin"
      
      wget -qO- "https://github.com/ko-build/ko/releases/download/v0.12.0/ko_0.12.0_Linux_x86_64.tar.gz" | tar -xvz ko
      install ./ko "$CI_PROJECT_DIR/bin/ko"
    - ci build --recipe com.github.google.ko --cosign-verify-key="$CI_PROJECT_DIR/internal/generators/sign/testdata/distroless.pub"  --slsa-version 1.0
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

integrate nib:
  stage: integrate
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/node:lts
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/static
    BUILD_IMAGE_PARENT: harbor.dcas.dev/ghcr.io/djcass44/nib/srv:v1.0.2
  cache:
    paths:
      - .cache
    key: nib
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
      - build.txt
  script:
    - |
      mkdir -p bin/
      mv ci bin/
      export PATH="$PATH:$CI_PROJECT_DIR/bin"
      
      wget -qO- "https://github.com/djcass44/nib/releases/download/v1.0.2/nib_1.0.2_linux_amd64.tar.gz" | tar -xvz nib
      install ./nib "$CI_PROJECT_DIR/bin/nib"
    - ci build --recipe com.github.djcass44.nib --skip-cosign-verify=true  --slsa-version 1.0
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

integrate jib:
  stage: integrate
  image: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/maven:19
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/java-maven
    AUTO_DEVOPS_MAVEN_SETTINGS_ARGS: "-mirror=prism=Prism=https://prism.v2.dcas.dev/api/v1/maven/-/=central"
    BUILD_IMAGE_PARENT: harbor.dcas.dev/registry.gitlab.com/av1o/base-images/tomcat-native:19
  cache:
    paths:
      - .cache
    key: mvn
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
      - build.txt
  script:
    - |
      mkdir -p ~/.m2
      /opt/mvn-settings-gen ${AUTO_DEVOPS_MAVEN_SETTINGS_ARGS} > ~/.m2/settings.xml
    - ./ci build --recipe com.google.cloud.tools.jib-maven-plugin --skip-cosign-verify=true
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

integrate buildkit:
  stage: integrate
  image: harbor.dcas.dev/docker.io/moby/buildkit:v0.11.3-rootless
  dependencies:
    - build binary
  needs:
    - build binary
  variables:
    PROJECT_PATH: samples/python
    KUBERNETES_POD_ANNOTATIONS_1: "container.apparmor.security.beta.kubernetes.io/build=unconfined"
    KUBERNETES_POD_ANNOTATIONS_2: "container.seccomp.security.alpha.kubernetes.io/build=unconfined"
  cache:
    paths:
      - .cache
    key: buildkit
  artifacts:
    paths:
      - sbom.cdx.json
      - provenance.slsa.json
      - build.txt
  script:
    - ./ci dockerfile --name python/micropipenv@v1
    - ./ci build --recipe com.github.moby.buildkit --slsa-version 1.0
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success
  <<: *rules

include:
#  - remote: https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/verify/Semgrep-Quality.gitlab-ci.yml
  - remote: https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/test/Go-Test.gitlab-ci.yml
